version: 2
project_name: rbchat
builds:
  - id: rbchat
    main: ./cmd/rbchat
    binary: rbchat
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.rbchatSecret={{ .Env.RBCHAT_SECRET }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
archives:
  - formats: [tar.gz]
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
