// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Config struct {
	Key   string
	Value string
}

type Message struct {
	ID        int64
	MessageID string
	Type      string
	Username  string
	Team      string
	Text      string
	Timestamp string
	Signature string
	NetworkID string
}
