// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getRecentMessagesForSync = `-- name: GetRecentMessagesForSync :many
SELECT id, message_id, type, username, team, text, timestamp, signature, network_id
FROM messages
WHERE signature != ''
  AND network_id = ?
ORDER BY id DESC
LIMIT ?
`

type GetRecentMessagesForSyncParams struct {
	NetworkID string
	Limit     int64
}

func (q *Queries) GetRecentMessagesForSync(ctx context.Context, arg GetRecentMessagesForSyncParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessagesForSync, arg.NetworkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Type,
			&i.Username,
			&i.Team,
			&i.Text,
			&i.Timestamp,
			&i.Signature,
			&i.NetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMessagesToday = `-- name: GetRecentMessagesToday :many
SELECT id, message_id, type, username, team, text, timestamp, signature, network_id
FROM messages
WHERE date(timestamp) = date('now')
  AND signature != ''
  AND network_id = ?
ORDER BY id DESC
LIMIT ?
`

type GetRecentMessagesTodayParams struct {
	NetworkID string
	Limit     int64
}

func (q *Queries) GetRecentMessagesToday(ctx context.Context, arg GetRecentMessagesTodayParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessagesToday, arg.NetworkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Type,
			&i.Username,
			&i.Team,
			&i.Text,
			&i.Timestamp,
			&i.Signature,
			&i.NetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (message_id, type, username, team, text, timestamp, signature, network_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(message_id) DO NOTHING
`

type InsertMessageParams struct {
	MessageID string
	Type      string
	Username  string
	Team      string
	Text      string
	Timestamp string
	Signature string
	NetworkID string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.MessageID,
		arg.Type,
		arg.Username,
		arg.Team,
		arg.Text,
		arg.Timestamp,
		arg.Signature,
		arg.NetworkID,
	)
	return err
}

const setConfig = `-- name: SetConfig :exec
INSERT OR REPLACE INTO config (key, value) VALUES (?, ?)
`

type SetConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}
